name: Pages

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check types
        run: npm run typecheck
